# Site settings
title: Eugene Melnyk
header-img: img/home-bg.jpg
icon: img/icon.png
copyright_name: Eugene Melnyk
description: "Eugene Melnyk's Blog"
baseurl: ""
url: "https://melgenek.github.io"
twitter_username: melgenek
github_username:  melgenek
#facebook_username:
linkedin_username: yevhenii-melnyk-75b892123
email_username:  melnyk.yevhenii@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: "UA-98252899-1"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: :title
paginate: 5
paginate_path: /page/:num
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
